numpy is a general purpose array processing package

## Why Use NumPy?

Python lists are excellent, general-purpose containers. They can be “heterogeneous”, meaning that they can contain elements of a variety of types, and they are quite fast when used to perform individual operations on a handful of elements.

Depending on the characteristics of the data and the types of operations that need to be performed, other containers may be more appropriate; by exploiting these characteristics, we can improve speed, reduce memory consumption, and offer a high-level syntax for performing a variety of common processing tasks. NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU.



### Arrays

array is a data structure which stores similiar types of data items in it it is different from list cause it can store only one type of data

In [1]:
import numpy as np

In [3]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)
#arr

In [5]:
#creating a 3D array
ls1=[1,2,3,4,5]
ls2=[6,7,8,9,0]
ls3=[0,9,7,5,4]

arr1=np.array([ls1,ls2,ls3])


In [8]:
arr1
arr1.shape #returns (row ,columns)

(3, 5)

In [13]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 0, 9],
       [7, 5, 4]])

In [15]:
#accessing an element
arr[3]

4

In [20]:
arr1[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [21]:
arr1[0:1,0:]

array([[1, 2, 3, 4, 5]])

In [22]:
arr1[1:3,2:4]

array([[8, 9],
       [7, 5]])

In [23]:
arr1[1:2,1:4]

array([[7, 8, 9]])

In [24]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
print(a[0])
print(a[0][0])
print(a[0,0])

[1 2 3 4]
1
1


In [28]:
a.shape

(3, 4)

<h6>note</h6>
It is familiar practice in mathematics to refer to elements of a matrix by the row index first and the column index second. This happens to be true for two-dimensional arrays, but a better mental model is to think of the column index as coming last and the row index as second to last. This generalizes to arrays with any number of dimensions.

In [30]:
type(a.shape) #tuple

tuple

In [33]:
print(a.ndim)
print(a.shape)
print(a.size,a.dtype)

2
(3, 4)
12 int64
