In [2]:
import numpy as np

## sorting in ndArrays

quick‐ sort algorithm, though mergesort and heapsort are also available. For most applica‐ tions, the default quicksort is more than sufficient.
To return a sorted version of the array without modifying the input, you can use np.sort:


In [3]:
a=np.array([2,4,1,6,5,3])
np.sort(a)

array([1, 2, 3, 4, 5, 6])

In [6]:
#If you prefer to sort the array in-place, you can instead use the sort method of arrays:
a.sort()
a

array([1, 2, 3, 4, 5, 6])

if you want the indices and manually sort the array we use argsort() method

In [11]:
x=np.array([2,1,5,4,3])
np.argsort(x)

array([1, 0, 4, 3, 2])

## Array Concatenation and Splitting

t’s also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We’ll take a look at those operations here.

In [20]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
z=np.array([[1,2,3,4]])
p=np.array([[4,5,6,7]])

In [17]:
#concatinating 1D arrays
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
np.concatenate([z,p])

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

## Basic operations in array

In [32]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])

array([0, 0, 1, 0])

In [33]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x.sum())
print(y.sum())


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
10
26


In [34]:
#advanced functions
#broadcast
d=x*25
d

array([ 25,  50,  75, 100])

In [37]:
# statistical functions
print(x.mean())

x.max()

2.5


4

In [38]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [39]:
a.sum(axis=1) #adding the columns

array([1.51832856, 1.55434556, 1.78690428])

In [40]:
a.sum()

4.8595784

In [42]:
a.shape

(3, 4)

In [41]:
a.sum(axis=0) #adding the rows

array([1.12378257, 1.04875507, 1.01034462, 1.67669614])