In [1]:
import numpy as np

### Basic arrays
<p>we will create an empty array , a zero array,an ones array</p>

In [4]:
z=np.zeros(3)

array([0., 0., 0.])

In [7]:
O=np.ones(5)

array([1., 1., 1., 1., 1.])

<h5>creating an array as for a given range</h5>

In [9]:
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [12]:
b=np.arange(2,11,2)
b

array([ 2,  4,  6,  8, 10])

You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:
it means Socho tumhaare paas ek lambi dor hai, aur tumhe us dor par kuch chhote-chhote nishaan (marks) lagane hain. Agar tum chahte ho ki dor ke shuru se lekar end tak 5 nishaan lagao, toh tum is baat ka dhyan rakhoge ki har nishaan ke beech ki doori ek jaisi ho.

NumPy mein, np.linspace() ek helper ki tarah hai jo yeh nishaan lagane mein madad karta hai, lekin dor par nahi, balki number line par.

Isse samajhte hain:

Start aur End Points: Tum ise batate ho ki kahan se shuru karna hai aur kahan khatam.
Number of Marks: Tum ise batate ho kitne nishaan (marks) chahiye.
Maan lo tumhe ek aisa array (numbers ki list) banana hai jo 0 se shuru ho aur 10 par khatam, aur tumhe is list mein 5 numbers chahiye. Tum np.linspace() aise use karoge:

In [13]:
c=np.linspace(1,15,6)
d=np.linspace(1,30,5)

print(c)
print(d)

[ 1.   3.8  6.6  9.4 12.2 15. ]
[ 1.    8.25 15.5  22.75 30.  ]
